#ifndef UI_WINDOW_H
# define UI_WINDOW_H

# include <windows.h>

# define IDC_COMBO_MODE				200
# define IDC_BTN_STOP				201
# define IDC_SLIDER_BRIGHT			202
# define IDC_STATIC_STATUS			203
# define IDC_BTN_AUTOSTART			205
# define IDT_TRAY_RETRY				3

# define IDC_BTN_COLOR_BREATH		210
# define IDC_SWATCH_BREATH			211
# define IDC_SLIDER_BSPEED			212
# define IDC_SLIDER_BSMOOTH			213

# define IDC_SLIDER_ANGLE			220
# define IDC_SLIDER_WSPEED			221

# define IDC_SLIDER_SPSPEED			230
# define IDC_SLIDER_SPDENS			231

# define IDC_BTN_COLOR_REACT		240
# define IDC_SWATCH_REACT			241
# define IDC_BTN_REACT_RANDOM		242
# define IDC_RADIO_SHORT			243
# define IDC_RADIO_MEDIUM			244
# define IDC_RADIO_LONG				245

# define IDC_CHK_WHEEL_REVERSE		250
# define IDC_SLIDER_WHSPEED			251

# define IDC_SLIDER_LTSPEED			261
# define IDC_SLIDER_LTSMOOTH		262
# define IDC_SLIDER_LTWIDTH			263
# define IDC_SLIDER_LTCONCUR		264
# define IDC_SLIDER_FLSPEED			265
# define IDC_SLIDER_FLSMOOTH		266
# define IDC_SLIDER_RNSPEED			267
# define IDC_RAIN_DENSITY_BASE		400
# define IDC_RAIN_COLORCNT_BASE		410
# define IDC_RAIN_COLOR_BASE		270
# define IDC_SLIDER_MXSPEED			280
# define IDC_MATRIX_DENSITY_BASE	420
# define IDC_MATRIX_COLORCNT_BASE	430
# define IDC_COMBO_MXSTYLE			282
# define IDC_MATRIX_COLOR_BASE		285

# define IDC_BTN_STATIC_HORIZ		500
# define IDC_BTN_STATIC_VERT		501
# define IDC_SLIDER_STATIC_ZONES	502
# define IDC_COMBO_STATIC_ZONESEL	503
# define IDC_BTN_STATIC_COLOR		504

# define WM_TRAYICON (WM_USER + 1)
# define IDC_TRAY_RESTORE			900
# define IDC_TRAY_EXIT				901

extern HWND		g_hComboMode;
extern HBRUSH	g_bgBrush;

LRESULT CALLBACK	WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp);

#endif
